### ISSUE TITLE
Non-segmented membranes

### ISSUE THREAD

**Issue by videomusik** [UCC-Organism/ucc-organism#13]
currently the membranes gets a jagged look where it is very visible that the membrane consists of line segments with 'straight' ends

**Comment by vorg** [comment]
This will take some time. Also it's not cheap. So even if I fix it for the membrane the same problem will stay for cells if they increase the cell border size > 5.

**Comment by vorg** [comment]
Fixed in https://github.com/UCC-Organism/ucc-organism/commit/dccff3616c6bc9944bb05d42f0430be7d92ade87
