### ISSUE TITLE
White lines overlay on "All" view in Plask app on Mac Mini

### ISSUE THREAD

**Issue by videomusik** [UCC-Organism/ucc-organism#21]
Only on the Mac Mini, not on laptop, the Plask App have lines across the visualisation when the cameraDistance is set higher than 0.8.
I have send you a screengrab from the MacMini with wetransfer where you can see that this also seems to be related to the "camera tilt" value, as the stripes get wider or narrow at the same cameraDistance when changing cameraTilt.

The colour of the lines seem to be that of the background as they change with that. Also the agents and their bleed' seems to 'override' the lines, so it could be a shader thing?

Attached screenshoot from video below.

![screen shot 2015-06-10 at 17 13 33](https://cloud.githubusercontent.com/assets/339971/8086186/5d383ad2-0f94-11e5-99f9-9d5b16848526.png)

**Comment by vorg** [comment]
Fixed by https://github.com/UCC-Organism/ucc-organism/commit/9d5299db92591faa7e6ca55abfbf1772d6e13591 ?

**Comment by videomusik** [comment]
Perfect. Working.
