### ISSUE TITLE
Optimise for Plask

### ISSUE THREAD

**Issue by videomusik** [UCC-Organism/ucc-organism#4]
Are there things in the code that can be done to make the App run faster in Plask?

**Comment by vorg** [comment]
Improved in
https://github.com/UCC-Organism/ucc-organism/commit/20a2e5d8165be38178caf6b98dcf8e909340401d
https://github.com/UCC-Organism/ucc-organism/commit/51f8b1ce3af701f4a9dc0489ec37039e6b00825f
https://github.com/UCC-Organism/ucc-organism/commit/79caa5c89b03c3f782903fa71b706112015e99c5
